### ISSUE TITLE
Detect Gimble beacon

### ISSUE THREAD

**Issue by bhaumik2712** [gimbalinc/hello-gimbal-android#1]
Hi,
I have registered gimble beacon on the Gimble Manager web portal.
I want to detect and list the nearby Gimble beacon with name and factory ID using gimble sdk.
Please help me out.

Regards,
Bhaumik

**Comment by gimbal-github-user** [comment]
Hi,

Please take a look at the following link that has the detailed information about how to get started with Gimbal https://docs.gimbal.com/android/v2/devguide.html. 

You send an email to support@gimbal.com for further assistance.

Thanks,
Gimbal

**Comment by bhaumik2712** [comment]
Thanks for support !!
